/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SnackBar: typeof import('./src/components/SnackBar.vue')['default']
    TaskFilter: typeof import('./src/components/tasks/TaskFilter.vue')['default']
    TaskForm: typeof import('./src/components/tasks/TaskForm.vue')['default']
    TaskTable: typeof import('./src/components/tasks/TaskTable.vue')['default']
    Topbar: typeof import('./src/components/layout/Topbar.vue')['default']
    TopBar: typeof import('./src/components/layout/TopBar.vue')['default']
  }
}
